version: '3.8'

services:
  pitest-runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # 构建参数，可以通过环境变量覆盖
        MAVEN_VERSION: ${MAVEN_VERSION:-3.8.5}
        PITEST_VERSION: ${PITEST_VERSION:-1.9.0}
        JAVA_VERSION: ${JAVA_VERSION:-8}
    image: ${DOCKER_REGISTRY:-localhost:5000}/${IMAGE_NAME:-distributed-pitest}:${IMAGE_TAG:-latest}
    container_name: pitest-runner-build

    # 构建时的环境变量
    environment:
      - MAVEN_OPTS=-Xmx1g -XX:+UseG1GC
      - JAVA_OPTS=-Xmx1g -XX:+UseG1GC

    # 健康检查
    healthcheck:
      test: ["CMD", "java", "-version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # 网络配置
    networks:
      - pitest-network

# 网络定义
networks:
  pitest-network:
    driver: bridge
    name: pitest-network